apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: geode-locator
spec:
  serviceName: "geode-locator"
  replicas: 1
  template:
    metadata:
      labels:
        name: geode-locator
        geode-locator: "true"
        role: locator
    spec:
      containers:
      - name: locator
        image: azwickey/geode
        command:
        - bash
        - /config/start.sh
        ports:
          - containerPort: 10334
        volumeMounts:
        - name: disk
          mountPath: /locator/data
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: "locator"
  volumeClaimTemplates:
  - metadata:
      name: disk
      annotations:
        volume.beta.kubernetes.io/storage-class: slow
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
