apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: geode-locator
spec:
  serviceName: "geode-locator"
  replicas: 1
  template:
    metadata:
      labels:
        name: geode-locator
        geode-locator: "true"
        role: locator
    spec:
      containers:
      - name: locator
        image: azwickey/geode
        command: ["/gfshWrapper.sh", "gfsh", "start", "locator", "--name=geode-locator"]
        ports:
          - containerPort: 10334
