apiVersion: v1
kind: ReplicationController
metadata:
  name: locator
spec:
  replicas: 1
  selector:
    geode-locator: "true"
  template:
    metadata:
      labels:
        name: geode-locator
        geode-locator: "true"
        role: locator
    spec:
      containers:
      - name: locator
        image: markito/geode:k8
        command: ["/gfshWrapper.sh", "gfsh", "start", "locator", "--name=locator1"]
        ports:
          - containerPort: 10334
