apiVersion: v1
kind: Service
metadata:
  labels:
    name: geode-locator
    role: locator
  name: locator-service
spec:
  ports:
  - port: 10334
    targetPort: 10334
  clusterIP: None
  selector:
    geode-locator: "true"
