apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: geode-locator
spec:
  serviceName: "geode-locator"
  replicas: 1
  template:
    metadata:
      labels:
        name: geode-locator
        geode-locator: "true"
        role: locator
    spec:
      containers:
      - name: locator
        image: azwickey/geode
        command: ["/gfshWrapper.sh", "gfsh", "start", "locator", "--name=geode-locator", "--dir=/locator/data"]
        ports:
          - containerPort: 10334
        volumeMounts:
        - name: disk
          mountPath: /locator/data
  volumeClaimTemplates:
  - metadata:
      name: disk
      annotations:
        volume.beta.kubernetes.io/storage-class: slow
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
