apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: geode-server
spec:
  serviceName: "geode-locator"
  replicas: 3
  template:
    metadata:
      labels:
        name: geode-server
        geode-server: "true"
        role: server
    spec:
      containers:
      - name: server
        image: azwickey/geode
        command: ["/startServer.sh"]
        ports:
          - containerPort: 40404
