apiVersion: v1
kind: Service
metadata:
  labels:
    name: server-service
    role: geode-server
  name: server-service
spec:
  ports:
  - port: 40404
    name: peer
  clusterIP: None
  selector:
    geode-server: "true"
