apiVersion: v1
kind: ReplicationController
metadata:
  name: server
spec:
  replicas: 1
  selector:
    geode-server: "true"
  template:
    metadata:
      labels:
        name: geode-server
        role: geode-server
    spec:
      containers:
      - name: server
        image: markito/geode:k8
        command: ["/gfshWrapper.sh", "gfsh", "start", "server", "--name=$HOSTNAME"]
        ports:
          - containerPort: 40404
