apiVersion: v1
kind: ReplicationController
metadata:
  name: geode-server
spec:
  replicas: 1
  selector:
    geode-server: "true"
  template:
    metadata:
      labels:
        name: geode-server
        geode-server: "true"
        role: server
    spec:
      containers:
      - name: server
        image: markito/geode:k8
        command: ["/gfshWrapper.sh", "gfsh", "start", "server", "--name=${HOSTNAME}", "--locators=${LOCATOR_SERVICE_SERVICE_HOST}:${LOCATOR_SERVICE_SERVICE_PORT}"]
        ports:
          - containerPort: 40404
