apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: geode-server
spec:
  serviceName: "geode-server"
  replicas: 3
  template:
    metadata:
      labels:
        name: geode-server
        geode-server: "true"
        role: server
    spec:
      containers:
      - name: server
        image: azwickey/geode
        command:
        - bash
        - /config/start.sh
        ports:
          - containerPort: 40404
        volumeMounts:
        - name: config
          mountPath: /config
        env:
          - name: GEODE_LOCATOR_HOST
            value: "geode-locator"
          - name: GEODE_LOCATOR_PORT
            value: "10334"
      volumes:
      - name: config
        configMap:
          name: "server"
