apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geode-server
spec:
  selector:
    matchLabels:
      app: geode-server
  serviceName: server-service
  replicas: 1
  template:
    metadata:
      labels:
        app: geode-server
        geode-server: "true"
        role: server
    spec:
      containers:
      - name: server
        image: alb3rtobr/geode-kubernetes:1.10.0
        command:
        - bash
        - /config/start.sh
        ports:
          - containerPort: 40404
        volumeMounts:
        - name: config
          mountPath: /config
        env:
          - name: GEODE_LOCATOR_HOST
            value: "geode-locator"
          - name: GEODE_LOCATOR_PORT
            value: "10334"
      volumes:
      - name: config
        configMap:
          name: "server"
