apiVersion: v1
kind: Service
metadata:
  name: {{.Values.geode_app.name}}-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    app: {{.Values.geode_app.name}}
