apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{.Values.geode_app.name}}-rs
  # labels so that we can bind a Service to this Pod
  labels:
    app: {{.Values.geode_app.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.geode_app.name}}
  template:
    metadata:
      labels:
        app: {{.Values.geode_app.name}}
    spec:
      containers:
      - name: app
        image: {{.Values.geode_app.image}}
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "pks"
          - name: LOCATOR_HOST
            value: "{{.Values.geode_locator.name}}-service"
          - name: LOCATOR_PORT
            value: "{{.Values.geode_locator.port}}"
