apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geode-locator
spec:
  selector:
    matchLabels:
      app: {{.Values.geode-locator.name}}
  serviceName: {{.Values.geode-locator.name}}-service
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Values.geode-locator.name}}
        geode-locator: "true"
        role: locator
    spec:
      containers:
      - name: locator
        image: {{.Values.geode-locator.image}}
        command:
        - bash
        - /config/start.sh
        ports:
          - containerPort: 10334
        volumeMounts:
        - name: disk
          mountPath: /locator/data
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: "locator"
  volumeClaimTemplates:
  - metadata:
      name: disk
      annotations:
        volume.beta.kubernetes.io/storage-class: standard
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
