locator:
  host: localhost
  port: 10334
tomcat:
  port: 8080
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
---
spring:
  profiles: pks
locator:
  host: ${LOCATOR_HOST:localhost}
  port: ${LOCATOR_PORT:10334}
