locator:
  host: localhost
  port: 10334
tomcat:
  port: 8080
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
---
spring:
  profiles: pks
locator:
  host: geode-locator
  port: 10334
