apiVersion: v1
kind: ConfigMap
metadata:
  name: locator
data:
  start.sh: |
    #!/bin/bash

    #Clean up stale PID from container exit
    rm -f /locator/data/vf.gf.locator.pid

    #Use API Server to determine locators
    KUBE_TOKEN=$(</var/run/secrets/kubernetes.io/serviceaccount/token)
    CERT_LOCATION=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    wget -vO- --ca-certificate $CERT_LOCATION --header "Authorization: Bearer $KUBE_TOKEN" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/default/endpoints/geode-locator > endpoints.txt
    cat endpoints.txt

    # NEED jq utility
    wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
    mv jq-linux64 jq
    chmod u+x jq
    LOCATORS=$(./jq ".subsets[].addresses[] | .hostname " endpoints.txt | tr -d '"')
    SERVICE=$(./jq ".metadata.name " endpoints.txt | tr -d '"')
    NAMESPACE=$(./jq ".metadata.namespace " endpoints.txt | tr -d '"')
    echo $LOCATORS
    echo $SERVICE
    echo $NAMESPACE
    set -f
    array=(${LOCATORS// / })
    for i in "${array[@]}"
      do
        if [[ $HOSTNAME != $i ]]; then
          if [[ -z $LOCATOR_STR ]]; then
            LOCATOR_STR=$i.$SERVICE.$NAMESPACE.svc.cluster.local[10334]
          else
            LOCATOR_STR=$LOCATOR_STR,$i.$SERVICE.$NAMESPACE.svc.cluster.local[10334]
          fi
        fi
        echo $LOCATOR_STR
    done
    JARS="/jars/metrics-publishing-service-1.0-SNAPSHOT.jar"

    ./gfshWrapper.sh gfsh start locator --name=${HOSTNAME} --locators=$LOCATOR_STR --classpath=$JARS --J=-Dprometheus.metrics.port=${GEODE_LOCATOR_METRICS_PORT} --dir=/locator/data --J=-Dlog4j.configurationFile=/config/log4j2.xml
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="FATAL" shutdownHook="disable" packages="org.apache.geode.internal.logging.log4j">
      <Properties>
        <Property name="geode-pattern">[%level{lowerCase=true} %date{yyyy/MM/dd HH:mm:ss.SSS z} &lt;%thread&gt; tid=%tid] %message%n%throwable%n</Property>
        <Property name="geode-default">true</Property>
      </Properties>
      <Appenders>
        <Console name="STDOUT" class="org.apache.log4j.ConsoleAppender">
          <param name="Target" value="System.out"/>
          <PatternLayout pattern="${geode-pattern}"/>
        </Console>
      </Appenders>
      <Loggers>
        <Logger name="com.gemstone" level="INFO" additivity="true"/>
        <Logger name="org.apache.geode" level="INFO" additivity="true">
          <filters>
            <MarkerFilter marker="GEODE_VERBOSE" onMatch="DENY" onMismatch="NEUTRAL"/>
          </filters>
        </Logger>
        <Logger name="org.jgroups" level="FATAL" additivity="true"/>
        <Logger name="org.eclipse.jetty" level="FATAL" additivity="true"/>
        <Root level="INFO">
          <AppenderRef ref="STDOUT"/>
        </Root>
      </Loggers>
    </Configuration>
