apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{.Values.geode_server.name}}-metrics-servicemonitor
  # Change this to the namespace the Prometheus instance is running in
  # namespace: default
  labels:
    app: {{.Values.geode_server.name}}
    release: prometheus
spec:
  selector:
    matchLabels:
      name: {{.Values.geode_server.name}}-service # target geode service
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
